name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare Stage
        run: |
          echo "Starting the pipeline"
          echo "Prepare stage completed!"

  build:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Stage
        run: |
          echo "Building the application..."
          echo "Hello, World! from the build stage"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test Stage
        run: |
          echo "Running tests..."
          echo "Hello, World! from the test stage"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Stage
        run: |
          echo "Deploying the application..."
          echo "Hello, World! from the deploy stage"

  cleanup:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cleanup Stage
        run: |
          echo "Cleaning up resources..."
          echo "Pipeline execution completed successfully!"
